#!/usr/bin/env python3
"""
gen_test_asc.py — Generate a minimal LTspice test schematic (.asc) for a
freshly-built symbol package.

The test schematic places one instance of the symbol, wires up supply
rails to detected power pins (V+ to a +15 V source, V- to GND or to a -15
V source if the model is bipolar), drives any input pin with a 1 kHz
small-signal source, leaves outputs floating, and includes a SPICE
directive based on the detected part type.

Reads JSON from stdin or --json-file with the same shape as gen_asy.py
expects, plus an optional `lib_filename` field naming the .lib to
include.

Outputs .asc text to stdout or --out.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

# Coordinate constants (LTspice grid is 16 px)
GRID = 16
SYMBOL_X = 256
SYMBOL_Y = 256


def emit_test_asc(model: dict[str, Any]) -> str:
    name = model["name"]
    part_type = model.get("part_type", "generic").lower()
    lib_file = model.get("lib_filename", f"{name}.lib")
    pins = model.get("pins", [])

    # Heuristic: pull power/input/output info from pin classifications.
    # We re-use a tiny copy of the classifier here to avoid the dependency.
    import re
    POWER_POS = re.compile(r"^(VCC|VDD|VS|VPLUS|VPOS|VP|VBAT|V\+|\+VS|VAA|AVCC|AVDD|DVCC|DVDD|VDDA|VDDD|VCCA|VCCD|\+V)\d*$", re.IGNORECASE)
    POWER_NEG = re.compile(r"^(GND|VSS|VEE|V-|VN|VNEG|VMINUS|-VS|0|COM|AGND|DGND|PGND|EGND|RTN|RETURN|-V)\d*$", re.IGNORECASE)
    NONINV    = re.compile(r"^(IN\+|\+IN|INP|IN_P|NONINV|VINP)$", re.IGNORECASE)
    INV       = re.compile(r"^(IN-|-IN|INN|IN_N|INV|VINM)$", re.IGNORECASE)
    INPUT     = re.compile(r"^(IN|INPUT|SIG|SIGNAL|VIN|INA|INB|IN\d+)$", re.IGNORECASE)
    OUTPUT    = re.compile(r"^(OUT|OUTPUT|VOUT|OUTA|OUTB|OUT\d+|Y|Q)$", re.IGNORECASE)

    pos_pins, neg_pins, in_pins, out_pins = [], [], [], []
    for p in pins:
        pname = p["name"] if isinstance(p, dict) else str(p)
        if POWER_POS.match(pname):
            pos_pins.append(pname)
        elif POWER_NEG.match(pname):
            neg_pins.append(pname)
        elif NONINV.match(pname) or INV.match(pname) or INPUT.match(pname):
            in_pins.append(pname)
        elif OUTPUT.match(pname):
            out_pins.append(pname)

    # Pick directive
    if part_type in ("opamp", "comparator"):
        directive = ".tran 0 5m 0 1u"
    elif part_type in ("diode", "zener", "tvs"):
        directive = ".dc V1 0 5 0.01"
    elif part_type in ("npn", "pnp", "nmos", "pmos", "njf", "pjf"):
        directive = ".op"
    else:
        directive = ".op"

    out: list[str] = []
    out.append("Version 4")
    out.append("SHEET 1 880 680")

    # Symbol instance
    out.append(f"SYMBOL {name} {SYMBOL_X} {SYMBOL_Y} R0")
    out.append(f"SYMATTR InstName U1")

    # Lib include
    out.append(f"TEXT 64 {SYMBOL_Y + 200} Left 2 !.include {lib_file}")

    # Add the directive
    out.append(f"TEXT 64 {SYMBOL_Y + 232} Left 2 !{directive}")

    # Determine supply topology.
    # Single-supply: negative pin is GND/VSS/COM/AGND/DGND/PGND (i.e. a ground name).
    # Bipolar: negative pin is VEE/V-/VSS-with-negative-supply (op-amp style).
    GROUND_NAMES = re.compile(
        r"^(GND|VSS|COM|AGND|DGND|PGND|EGND|RTN|RETURN|0)$", re.IGNORECASE
    )
    is_single_supply = all(GROUND_NAMES.match(n) for n in neg_pins) if neg_pins else True

    if pos_pins:
        vcc_val = "3.3" if is_single_supply else "15"
        out.append(f"SYMBOL voltage 64 96 R0")
        out.append(f"SYMATTR InstName V_VCC")
        out.append(f"SYMATTR Value {vcc_val}")
        out.append(f"FLAG 64 64 VCC")
    if neg_pins and not is_single_supply:
        out.append(f"SYMBOL voltage 144 96 R0")
        out.append(f"SYMATTR InstName V_VEE")
        out.append(f"SYMATTR Value -15")
        out.append(f"FLAG 144 64 VEE")
    if in_pins:
        # signal source
        out.append(f"SYMBOL voltage 64 320 R0")
        out.append(f"SYMATTR InstName V_IN")
        out.append(f"SYMATTR Value SINE(0 0.1 1k)")
        out.append(f"FLAG 64 288 SIG_IN")

    # Helpful comment block
    out.append(f"TEXT 64 32 Left 2 ;Test rig generated by ltspice-symbol-creation skill")
    out.append(f"TEXT 64 64 Left 2 ;Wire the symbol pins to: VCC, VEE, SIG_IN, and your output node.")
    out.append(f"TEXT 64 96 Left 2 ;Pin map (declaration order = SpiceOrder):")
    for i, p in enumerate(pins, start=1):
        pname = p["name"] if isinstance(p, dict) else str(p)
        out.append(f"TEXT 64 {96 + i*16} Left 2 ;  {i}. {pname}")

    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json-file")
    ap.add_argument("--out")
    args = ap.parse_args()

    if args.json_file:
        with open(args.json_file) as f:
            model = json.load(f)
    else:
        model = json.load(sys.stdin)

    asc = emit_test_asc(model)
    if args.out:
        Path(args.out).write_text(asc)
    else:
        sys.stdout.write(asc)
    return 0


if __name__ == "__main__":
    sys.exit(main())
