#!/usr/bin/env python3
"""
write_cir.py — Build an LTspice-friendly .cir file from a structured description.

Usage (as a library):
    from write_cir import write_cir, Component, Source, Model

    netlist = write_cir(
        title="Non-inverting amplifier",
        components=[
            Component("R1", "N003", "0", "1k"),
            Component("R2", "N003", "OUT", "10k"),
            ...
        ],
        sources=[
            Source("V1", "VCC", "0", "DC 9"),
            Source("V2", "IN",  "0", "SINE(0 0.1 1k) AC 1"),
        ],
        subckt_calls=[
            ("XU1", ["N002","N003","VCC","0","OUT"], "UniversalOpAmp2",
             "Avol=1Meg GBW=1.1Meg Slew=0.5Meg"),
        ],
        models=[],                    # .model cards
        subckt_bodies=[],             # full .subckt ... .ends blocks for unknown ICs
        analyses=[".ac dec 100 1 1Meg", ".tran 0 5m 0 1u", ".op"],
        save_nets=["IN","OUT","N002","N003"],
        out_path="/tmp/amp.cir",
    )

Usage (as a CLI, reading a JSON spec):
    python write_cir.py spec.json out.cir
"""

from __future__ import annotations
import json, sys, datetime, re, pathlib
from dataclasses import dataclass, field
from typing import List, Tuple, Optional


# --- Data classes -----------------------------------------------------------

@dataclass
class Component:
    refdes: str
    n1: str
    n2: str
    value_or_model: str
    extra: str = ""          # e.g. "ic=0" for a cap, or model params

@dataclass
class Source:
    refdes: str              # must start with V or I
    nplus: str
    nminus: str
    spec: str                # e.g. "DC 9", "AC 1", "SINE(0 0.1 1k) AC 1"


# --- Validation -------------------------------------------------------------

_VALID_UNITS = {"T","G","Meg","K","k","M","m","u","n","p","f"}
_UNICODE_BANNED = ["µ", "Ω", "\u03BC", "\u03A9"]

def _scrub_value(v: str) -> str:
    """Flag obvious LTspice-unfriendly value strings. Returns sanitized v."""
    for bad in _UNICODE_BANNED:
        if bad in v:
            raise ValueError(f"Value {v!r} contains unicode LTspice won't parse; use ASCII (e.g. 'u' not 'µ', drop 'Ω').")
    # 'uF' / 'pF' / 'Hz' / 'ohm' suffixes are legal in LTspice but by convention we
    # strip them so the netlist is tidy.
    for junk in ["Ohm", "ohm", "Hz", "hz", "F", "H"]:
        # Only strip the very last character if it looks like a bare unit
        if v.endswith(junk) and len(v) > len(junk):
            v = v[:-len(junk)]
            break
    return v


def _validate_refdes(refdes: str, expected_letter: Optional[str] = None):
    if not refdes or not refdes[0].isalpha():
        raise ValueError(f"RefDes {refdes!r} must start with a letter.")
    if expected_letter and refdes[0].upper() != expected_letter:
        raise ValueError(f"RefDes {refdes!r} must start with {expected_letter!r}.")


# --- Main writer ------------------------------------------------------------

def write_cir(
    *,
    title: str,
    components: List[Component] = (),
    sources: List[Source] = (),
    subckt_calls: List[Tuple[str, List[str], str, str]] = (),
    models: List[str] = (),
    subckt_bodies: List[str] = (),
    analyses: List[str] = (),
    save_nets: List[str] = (),
    out_path: Optional[str] = None,
    options: List[str] = (),
) -> str:
    lines: List[str] = []
    date = datetime.date.today().isoformat()
    lines.append(f"* {title}")
    lines.append(f"* Generated by Claude LTspice_simulation skill on {date}")
    lines.append("")

    # Sources first — easier for humans to read
    if sources:
        lines.append("* --- Sources ---")
        for s in sources:
            _validate_refdes(s.refdes)
            if s.refdes[0].upper() not in {"V", "I"}:
                raise ValueError(f"Source {s.refdes!r} must start with V or I.")
            lines.append(f"{s.refdes} {s.nplus} {s.nminus} {s.spec}")
        lines.append("")

    # Components
    if components:
        lines.append("* --- Components ---")
        for c in components:
            _validate_refdes(c.refdes)
            val = _scrub_value(c.value_or_model)
            extra = f" {c.extra}" if c.extra else ""
            lines.append(f"{c.refdes} {c.n1} {c.n2} {val}{extra}")
        lines.append("")

    # Subcircuit calls (X-cards)
    if subckt_calls:
        lines.append("* --- Subcircuit calls ---")
        for refdes, pins, name, params in subckt_calls:
            _validate_refdes(refdes, "X")
            pin_str = " ".join(pins)
            extra = f" {params}" if params else ""
            lines.append(f"{refdes} {pin_str} {name}{extra}")
        lines.append("")

    # Models and subckt bodies
    if models:
        lines.append("* --- Models ---")
        for m in models:
            lines.append(m.strip())
        lines.append("")

    if subckt_bodies:
        lines.append("* --- Subcircuits ---")
        for body in subckt_bodies:
            lines.append(body.strip())
            lines.append("")

    # Options
    if options:
        lines.append("* --- Options ---")
        for opt in options:
            if not opt.lstrip().startswith("."):
                opt = ".options " + opt
            lines.append(opt)
        lines.append("")

    # Analysis directives
    if analyses:
        lines.append("* --- Analysis ---")
        for a in analyses:
            if not a.lstrip().startswith("."):
                raise ValueError(f"Analysis directive must start with '.': {a!r}")
            lines.append(a)
        lines.append("")

    # Save directives
    if save_nets:
        save_str = " ".join(f"V({n})" for n in save_nets)
        lines.append(f".save {save_str}")
        lines.append("")

    lines.append(".end")
    lines.append("")

    netlist = "\n".join(lines)

    if out_path:
        pathlib.Path(out_path).write_text(netlist, encoding="ascii")
    return netlist


# --- CLI entry point --------------------------------------------------------

def _from_spec(spec: dict) -> str:
    components = [Component(**c) for c in spec.get("components", [])]
    sources = [Source(**s) for s in spec.get("sources", [])]
    subckt_calls = [tuple(x) for x in spec.get("subckt_calls", [])]
    return write_cir(
        title=spec.get("title", "Untitled circuit"),
        components=components,
        sources=sources,
        subckt_calls=subckt_calls,
        models=spec.get("models", []),
        subckt_bodies=spec.get("subckt_bodies", []),
        analyses=spec.get("analyses", []),
        save_nets=spec.get("save_nets", []),
        options=spec.get("options", []),
        out_path=spec.get("out_path"),
    )


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("usage: python write_cir.py spec.json out.cir", file=sys.stderr)
        sys.exit(2)
    spec = json.loads(pathlib.Path(sys.argv[1]).read_text())
    spec["out_path"] = sys.argv[2]
    netlist = _from_spec(spec)
    print(f"wrote {sys.argv[2]} ({len(netlist.splitlines())} lines)")
